name: Multiverse-Portals
main: com.onarandombox.MultiversePortals.MultiversePortals
authors: ['Rigby', 'fernferret']
version: maven-version-number
api-version: 1.13
depend: ['Multiverse-Core']
softdepend: ['WorldEdit']
# Base commands are now defined in Multiverse-Core.